    create: {
      tenantId: tenant.id,
      siteName: body.siteName ?? 'e-Ventschau',
      logoUrl: body.logoUrl ?? null,
      backgroundImage: body.backgroundImage ?? null,
      darkMode: body.darkMode ?? true,
      themeSlug: body.themeSlug ?? 'noir',
      logoMode: body.logoMode ?? 'auto',
      openaiModel: body.openaiModel ?? 'auto',
      ...openaiKeyUpdate,
      ...socialLinksUpdate,
      ...contactAddressUpdate,
    },
